// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kanosdk.proto

package kanosdk

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StreamRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Request              *Request `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_kanosdk_42878e3d9b3e38cb, []int{0}
}
func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (dst *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(dst, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StreamRequest) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

type StreamResponse struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Response             *Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *StreamResponse) Reset()         { *m = StreamResponse{} }
func (m *StreamResponse) String() string { return proto.CompactTextString(m) }
func (*StreamResponse) ProtoMessage()    {}
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_kanosdk_42878e3d9b3e38cb, []int{1}
}
func (m *StreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamResponse.Unmarshal(m, b)
}
func (m *StreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamResponse.Marshal(b, m, deterministic)
}
func (dst *StreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamResponse.Merge(dst, src)
}
func (m *StreamResponse) XXX_Size() int {
	return xxx_messageInfo_StreamResponse.Size(m)
}
func (m *StreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StreamResponse proto.InternalMessageInfo

func (m *StreamResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StreamResponse) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

type Request struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Params               []*Param `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_kanosdk_42878e3d9b3e38cb, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetParams() []*Param {
	if m != nil {
		return m.Params
	}
	return nil
}

type Param struct {
	Mode                 string   `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Param) Reset()         { *m = Param{} }
func (m *Param) String() string { return proto.CompactTextString(m) }
func (*Param) ProtoMessage()    {}
func (*Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_kanosdk_42878e3d9b3e38cb, []int{3}
}
func (m *Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Param.Unmarshal(m, b)
}
func (m *Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Param.Marshal(b, m, deterministic)
}
func (dst *Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Param.Merge(dst, src)
}
func (m *Param) XXX_Size() int {
	return xxx_messageInfo_Param.Size(m)
}
func (m *Param) XXX_DiscardUnknown() {
	xxx_messageInfo_Param.DiscardUnknown(m)
}

var xxx_messageInfo_Param proto.InternalMessageInfo

func (m *Param) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *Param) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Response struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Detail               *Detail  `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_kanosdk_42878e3d9b3e38cb, []int{4}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Response) GetDetail() *Detail {
	if m != nil {
		return m.Detail
	}
	return nil
}

type Detail struct {
	Proximity            int32    `protobuf:"varint,1,opt,name=proximity,proto3" json:"proximity,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Detail) Reset()         { *m = Detail{} }
func (m *Detail) String() string { return proto.CompactTextString(m) }
func (*Detail) ProtoMessage()    {}
func (*Detail) Descriptor() ([]byte, []int) {
	return fileDescriptor_kanosdk_42878e3d9b3e38cb, []int{5}
}
func (m *Detail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Detail.Unmarshal(m, b)
}
func (m *Detail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Detail.Marshal(b, m, deterministic)
}
func (dst *Detail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Detail.Merge(dst, src)
}
func (m *Detail) XXX_Size() int {
	return xxx_messageInfo_Detail.Size(m)
}
func (m *Detail) XXX_DiscardUnknown() {
	xxx_messageInfo_Detail.DiscardUnknown(m)
}

var xxx_messageInfo_Detail proto.InternalMessageInfo

func (m *Detail) GetProximity() int32 {
	if m != nil {
		return m.Proximity
	}
	return 0
}

func (m *Detail) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Detail) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*StreamRequest)(nil), "kanosdk.StreamRequest")
	proto.RegisterType((*StreamResponse)(nil), "kanosdk.StreamResponse")
	proto.RegisterType((*Request)(nil), "kanosdk.Request")
	proto.RegisterType((*Param)(nil), "kanosdk.Param")
	proto.RegisterType((*Response)(nil), "kanosdk.Response")
	proto.RegisterType((*Detail)(nil), "kanosdk.Detail")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnectorClient is the client API for Connector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectorClient interface {
	Communicate(ctx context.Context, opts ...grpc.CallOption) (Connector_CommunicateClient, error)
}

type connectorClient struct {
	cc *grpc.ClientConn
}

func NewConnectorClient(cc *grpc.ClientConn) ConnectorClient {
	return &connectorClient{cc}
}

func (c *connectorClient) Communicate(ctx context.Context, opts ...grpc.CallOption) (Connector_CommunicateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Connector_serviceDesc.Streams[0], "/kanosdk.Connector/Communicate", opts...)
	if err != nil {
		return nil, err
	}
	x := &connectorCommunicateClient{stream}
	return x, nil
}

type Connector_CommunicateClient interface {
	Send(*StreamRequest) error
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type connectorCommunicateClient struct {
	grpc.ClientStream
}

func (x *connectorCommunicateClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *connectorCommunicateClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConnectorServer is the server API for Connector service.
type ConnectorServer interface {
	Communicate(Connector_CommunicateServer) error
}

func RegisterConnectorServer(s *grpc.Server, srv ConnectorServer) {
	s.RegisterService(&_Connector_serviceDesc, srv)
}

func _Connector_Communicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConnectorServer).Communicate(&connectorCommunicateServer{stream})
}

type Connector_CommunicateServer interface {
	Send(*StreamResponse) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type connectorCommunicateServer struct {
	grpc.ServerStream
}

func (x *connectorCommunicateServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *connectorCommunicateServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Connector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kanosdk.Connector",
	HandlerType: (*ConnectorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Communicate",
			Handler:       _Connector_Communicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "kanosdk.proto",
}

func init() { proto.RegisterFile("kanosdk.proto", fileDescriptor_kanosdk_42878e3d9b3e38cb) }

var fileDescriptor_kanosdk_42878e3d9b3e38cb = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xd1, 0x4e, 0xf2, 0x30,
	0x18, 0xfd, 0x37, 0xd8, 0x60, 0x1f, 0x81, 0x5f, 0x1b, 0x82, 0x8b, 0xf1, 0x82, 0xf4, 0x42, 0x17,
	0x13, 0x89, 0xe2, 0x23, 0xc0, 0xbd, 0x58, 0x9e, 0xa0, 0xd2, 0x26, 0x36, 0xd0, 0x76, 0x76, 0xc5,
	0xc8, 0xdb, 0x9b, 0x75, 0x5d, 0x9d, 0xd1, 0xc4, 0xbb, 0xef, 0x9c, 0xd3, 0x9d, 0x73, 0xf6, 0xb5,
	0x30, 0xde, 0x53, 0xa5, 0x2b, 0xb6, 0x5f, 0x94, 0x46, 0x5b, 0x8d, 0x06, 0x1e, 0xe2, 0x27, 0x18,
	0x6f, 0xad, 0xe1, 0x54, 0x12, 0xfe, 0x76, 0xe4, 0x95, 0x45, 0x08, 0xfa, 0x8a, 0x4a, 0x9e, 0x47,
	0xf3, 0xa8, 0xc8, 0x88, 0x9b, 0xd1, 0x2d, 0x0c, 0x4c, 0x23, 0xe7, 0xf1, 0x3c, 0x2a, 0x46, 0xcb,
	0xb3, 0x45, 0x6b, 0xe7, 0x3f, 0x23, 0xed, 0x01, 0xbc, 0x85, 0x49, 0x6b, 0x58, 0x95, 0x5a, 0x55,
	0xfc, 0x57, 0xc7, 0x3b, 0x18, 0x1a, 0xaf, 0x7b, 0xcb, 0xf3, 0x8e, 0x65, 0x23, 0x90, 0x70, 0x04,
	0x4b, 0x18, 0x74, 0xfa, 0xd9, 0x53, 0x19, 0xdc, 0xea, 0x19, 0x4d, 0x20, 0x16, 0xcc, 0xf9, 0x64,
	0x24, 0x16, 0x0c, 0xcd, 0x20, 0x95, 0xdc, 0xbe, 0x6a, 0x96, 0xf7, 0x1c, 0xe7, 0x11, 0xba, 0x86,
	0xb4, 0xa4, 0x86, 0xca, 0x2a, 0xef, 0xcf, 0x7b, 0xc5, 0x68, 0x39, 0x09, 0x99, 0x9b, 0x9a, 0x26,
	0x5e, 0xc5, 0x0f, 0x90, 0x38, 0xa2, 0x0e, 0x93, 0x9a, 0x85, 0xb0, 0x7a, 0x46, 0x53, 0x48, 0xde,
	0xe9, 0xe1, 0xc8, 0x7d, 0x5e, 0x03, 0xf0, 0x1e, 0x86, 0xdd, 0x1f, 0xfe, 0xb3, 0x62, 0xbb, 0x94,
	0x5e, 0x67, 0x29, 0x37, 0x90, 0x32, 0x6e, 0xa9, 0x38, 0xe4, 0x7d, 0xb7, 0x92, 0xff, 0xa1, 0xde,
	0xda, 0xd1, 0xc4, 0xcb, 0x78, 0x03, 0x69, 0xc3, 0xa0, 0x2b, 0xc8, 0x4a, 0xa3, 0x3f, 0x84, 0x14,
	0xf6, 0xe4, 0xf2, 0x12, 0xf2, 0x45, 0x84, 0x22, 0x71, 0xa7, 0xc8, 0x14, 0x12, 0x6e, 0x8c, 0x36,
	0x3e, 0xb9, 0x01, 0xcb, 0x67, 0xc8, 0x56, 0x5a, 0x29, 0xbe, 0xb3, 0xda, 0xa0, 0x35, 0x8c, 0x56,
	0x5a, 0xca, 0xa3, 0x12, 0x3b, 0x6a, 0x39, 0x9a, 0x85, 0x1a, 0xdf, 0x5e, 0xca, 0xe5, 0xc5, 0x0f,
	0xde, 0xdf, 0xd6, 0xbf, 0x22, 0xba, 0x8f, 0x5e, 0x52, 0xf7, 0xd2, 0x1e, 0x3f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x22, 0xf2, 0x2c, 0x46, 0x7a, 0x02, 0x00, 0x00,
}
